[project]
name = "weasyprint-server"
version = "0.0.1"
description = "html to pdf server"
readme = "README.md"

dependencies = [
  "weasyprint",
  "flask",
  "sentry-sdk",
  "pyuwsgi",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.2",
]
